---
name: Nightly Build
on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

jobs:
  check:
    name: Check new commits
    runs-on: ubuntu-latest
    outputs:
      new_commit_count: ${{ steps.get_new_commits.outputs.commit_count }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Get new commits
        id: get_new_commits
        run: echo "commit_count=$(git log --oneline --since '24 hours ago' | wc -l | tr -d ' ')" >> $GITHUB_OUTPUT
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    needs: check
    if: needs.check.outputs.new_commit_count > 0
    with:
      build-blade: true
      lint: true
      unit-test: true
      e2e-polybft-test: true
      e2e-legacy-test: true
      property-polybft-test: true
      fuzz-test: true
      benchmark-test: true
  notification_nightly:
    name: Nightly Notification
    uses: ./.github/workflows/notification-nightly.yml
    needs: ci
    if: success() || failure()
    with:
      environment: nightly
      build_blade_output: ${{ needs.ci.outputs.build-blade }}
      lint_output: ${{ needs.ci.outputs.lint }}
      unit_test_output: ${{ needs.ci.outputs.unit-test }}
      e2e_polybft_test_output: ${{ needs.ci.outputs.e2e-polybft-test }}
      e2e_legacy_test_output: ${{ needs.ci.outputs.e2e-legacy-test }}
      property_polybft_test_output: ${{ needs.ci.outputs.property-polybft-test }}
      fuzz_test_output: ${{ needs.ci.outputs.fuzz-test }}
      benchmark_test_output: ${{ needs.ci.outputs.benchmark-test }}
    secrets:
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
